-- Supabase schema contract for AI Blogpost.
-- Keep this file aligned with apps/web/src/lib/types.ts and services/ingest/src/database.py.

create extension if not exists pgcrypto;

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  slug text not null unique,
  title text not null,
  tldr jsonb,
  content text,
  excerpt text,
  cover_image text,
  is_published boolean not null default false,
  published_at timestamptz,
  source_url jsonb,
  ai_model text
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  slug text not null unique
);

create table if not exists public.post_tags (
  post_id uuid not null references public.posts(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, tag_id)
);

create table if not exists public.ai_generation_logs (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  topic text not null,
  source_name text,
  source_url text,
  status text not null,
  selected_model text,
  failure_reason text,
  output_json jsonb,
  validated boolean not null default false
);

create table if not exists public.post_moderation_events (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id),
  action text not null check (action in ('UNPUBLISH')),
  reason text,
  previous_is_published boolean not null,
  new_is_published boolean not null,
  created_by text not null,
  created_at timestamptz not null default now()
);

comment on table public.post_moderation_events is
  'Admin-owned audit log for post visibility changes. Written by the Spring Boot admin backend.';

create table if not exists public.topic_guidance (
  id uuid primary key default gen_random_uuid(),
  keyword text not null,
  normalized_keyword text not null,
  weight integer not null default 1 check (weight between 1 and 5),
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'DEACTIVATED')),
  expires_at timestamptz not null,
  created_by text not null,
  created_at timestamptz not null default now(),
  deactivated_by text,
  deactivated_at timestamptz,
  constraint topic_guidance_keyword_length check (char_length(keyword) between 2 and 120),
  constraint topic_guidance_normalized_keyword_length check (char_length(normalized_keyword) between 2 and 120)
);

comment on table public.topic_guidance is
  'Admin-owned editorial guidance. Written by the Spring Boot admin backend and read by the Python ingestion worker.';

create index if not exists posts_published_at_idx
  on public.posts (published_at desc)
  where is_published = true;

create index if not exists posts_source_url_gin_idx
  on public.posts using gin (source_url);

create index if not exists post_tags_tag_id_idx
  on public.post_tags (tag_id);

create index if not exists ai_generation_logs_created_at_idx
  on public.ai_generation_logs (created_at desc);

create index if not exists post_moderation_events_post_id_idx
  on public.post_moderation_events (post_id);

create index if not exists post_moderation_events_created_at_idx
  on public.post_moderation_events (created_at desc);

create index if not exists topic_guidance_active_idx
  on public.topic_guidance (status, expires_at);

create index if not exists topic_guidance_created_at_idx
  on public.topic_guidance (created_at desc);

create unique index if not exists topic_guidance_active_keyword_uidx
  on public.topic_guidance (normalized_keyword)
  where status = 'ACTIVE';

create table if not exists public.rss_sources (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  url text not null unique,
  is_active boolean not null default true,
  last_fetched_at timestamptz,
  error_count integer default 0,
  created_at timestamptz not null default now()
);

comment on table public.rss_sources is
  'Admin-owned RSS feeds. Written by the Spring Boot admin backend and read by the Python ingestion worker.';

create index if not exists rss_sources_is_active_idx
  on public.rss_sources (is_active);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  parent_id uuid references public.comments(id) on delete cascade,
  author_type text not null check (author_type in ('human', 'ai', 'anonymous')),
  author_name text,
  author_user_id text,
  body text not null check (char_length(body) between 1 and 5000),
  ai_model text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'spam')),
  moderated_by text,
  moderated_at timestamptz,
  created_at timestamptz not null default now(),
  constraint comments_moderation_consistent check (
    (status = 'pending' and moderated_by is null and moderated_at is null)
    or (status in ('approved', 'rejected', 'spam'))
  )
);

comment on table public.comments is
  'Human/AI comments on posts. Public reads only approved rows; writes moderated via status.';

create index if not exists comments_post_created_idx
  on public.comments (post_id, created_at desc)
  where status = 'approved';

create index if not exists comments_parent_id_idx
  on public.comments (parent_id);

create index if not exists comments_status_created_idx
  on public.comments (status, created_at desc);

-- First RLS in repo: anon key is public, so enforce approved-only reads at DB level.
alter table public.comments enable row level security;

drop policy if exists comments_read_approved on public.comments;

create policy comments_read_approved on public.comments
  for select to anon using (status = 'approved');

-- Raw-SQL migrations get no auto-grants: anon reads need this explicitly,
-- otherwise the web section silently renders empty (42501).
grant select on public.comments to anon;
