-- Supabase schema contract for AI Blogpost.
-- Keep this file aligned with apps/web/src/lib/types.ts and services/ingest/src/database.py.

create extension if not exists pgcrypto;

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  slug text not null unique,
  title text not null,
  tldr jsonb,
  content text,
  excerpt text,
  cover_image text,
  is_published boolean not null default false,
  published_at timestamptz,
  source_url jsonb,
  ai_model text
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  slug text not null unique
);

create table if not exists public.post_tags (
  post_id uuid not null references public.posts(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, tag_id)
);

create table if not exists public.ai_generation_logs (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  topic text not null,
  source_name text,
  source_url text,
  status text not null,
  selected_model text,
  failure_reason text,
  output_json jsonb,
  validated boolean not null default false
);

create index if not exists posts_published_at_idx
  on public.posts (published_at desc)
  where is_published = true;

create index if not exists posts_source_url_gin_idx
  on public.posts using gin (source_url);

create index if not exists post_tags_tag_id_idx
  on public.post_tags (tag_id);

create index if not exists ai_generation_logs_created_at_idx
  on public.ai_generation_logs (created_at desc);
